// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAToeFNgNsd4SdS99zvRE43cGQsrYDcLh0',
    appId: '1:1094210138859:web:11b5f5831c26fefdfc84ae',
    messagingSenderId: '1094210138859',
    projectId: 'finalproject-7f04b',
    authDomain: 'finalproject-7f04b.firebaseapp.com',
    storageBucket: 'finalproject-7f04b.firebasestorage.app',
    measurementId: 'G-MVE813J4SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5cX-BKnm3SJUFz8vvqMfdJPcHyaJM-8g',
    appId: '1:1094210138859:android:74b26ef5d2b3e9ddfc84ae',
    messagingSenderId: '1094210138859',
    projectId: 'finalproject-7f04b',
    storageBucket: 'finalproject-7f04b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDLgTZUjBgqp87NB4zdtDFwn40tF0ZBw',
    appId: '1:1094210138859:ios:9c2904934b3887e2fc84ae',
    messagingSenderId: '1094210138859',
    projectId: 'finalproject-7f04b',
    storageBucket: 'finalproject-7f04b.firebasestorage.app',
    iosClientId: '1094210138859-v4isnnp498l2fkmatkft3sa3hj6j7qqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARDLgTZUjBgqp87NB4zdtDFwn40tF0ZBw',
    appId: '1:1094210138859:ios:9c2904934b3887e2fc84ae',
    messagingSenderId: '1094210138859',
    projectId: 'finalproject-7f04b',
    storageBucket: 'finalproject-7f04b.firebasestorage.app',
    iosClientId: '1094210138859-v4isnnp498l2fkmatkft3sa3hj6j7qqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAToeFNgNsd4SdS99zvRE43cGQsrYDcLh0',
    appId: '1:1094210138859:web:5546c85cd751bcf5fc84ae',
    messagingSenderId: '1094210138859',
    projectId: 'finalproject-7f04b',
    authDomain: 'finalproject-7f04b.firebaseapp.com',
    storageBucket: 'finalproject-7f04b.firebasestorage.app',
    measurementId: 'G-KCX69VZ927',
  );

}